import {
  getPrintDimensionsForPageSize,
  normalizePdfRenderOptions,
  renderPdfHtml,
  type PdfDocumentModel,
  type PdfRenderOptions,
} from "@/services/pdf-export-template";

function createBaseModel(): PdfDocumentModel {
  return {
    appName: "SteuerFuchs",
    reportTitle: "Tax Export Report",
    taxYear: 2026,
    generatedDateLabel: "17 Mar 2026, 20:00",
    generatedAtIso: "2026-03-17T19:00:00.000Z",
    locale: "en-AT",
    currency: "EUR",
    includeDetailPages: false,
    selectedItemsLabel: "Selected Items",
    deductibleLabel: "Deductible This Year",
    refundLabel: "Estimated Refund",
    selectedItemCount: 2,
    deductibleTotal: "EUR 420.00",
    estimatedRefundTotal: "EUR 168.00",
    tableRows: [
      {
        title: "Laptop",
        date: "2026-01-05",
        category: "Hardware",
        usagePercent: "80%",
        price: "EUR 1000.00",
        deductible: "EUR 800.00",
      },
      {
        title: "Headset",
        date: "2026-02-01",
        category: "Office",
        usagePercent: "50%",
        price: "EUR 80.00",
        deductible: "EUR 40.00",
      },
    ],
    detailSections: [],
    imageAppendixGroups: [],
    nonImageAttachments: [],
    disclaimerText: "Not legal advice.",
    footerLine: "Generated by SteuerFuchs",
  };
}

describe("pdf-export-template", () => {
  it("normalizes render options with defaults", () => {
    const options = normalizePdfRenderOptions();
    expect(options).toEqual({
      pageSize: "A4",
      imageLayout: "HYBRID",
      imageQuality: "HIGH",
    });
  });

  it("uses explicit render option overrides", () => {
    const options = normalizePdfRenderOptions({
      pageSize: "LETTER",
      imageQuality: "COMPACT",
    });
    expect(options).toEqual({
      pageSize: "LETTER",
      imageLayout: "HYBRID",
      imageQuality: "COMPACT",
    });
  });

  it("returns expected print dimensions for A4", () => {
    expect(getPrintDimensionsForPageSize("A4")).toEqual({
      width: 595,
      height: 842,
      cssPageSize: "A4",
    });
  });

  it("renders summary and table sections", () => {
    const model = createBaseModel();
    const options: PdfRenderOptions = {
      pageSize: "A4",
      imageLayout: "HYBRID",
      imageQuality: "HIGH",
    };

    const html = renderPdfHtml(model, options);
    expect(html).toContain("Tax Export Report");
    expect(html).toContain("Selected Items");
    expect(html).toContain("Laptop");
    expect(html).toContain("@page");
    expect(html).toContain("size: A4");
    expect(html).not.toContain("Item Details");
    expect(html).not.toContain("Attachment Appendix");
  });

  it("renders detail and appendix sections with embedded image data URIs", () => {
    const model = createBaseModel();
    model.includeDetailPages = true;
    model.detailSections = [
      {
        itemId: "item-1",
        title: "Laptop",
        purchaseDate: "2026-01-05",
        vendor: "Example Store",
        category: "Hardware",
        usageLabel: "MIXED (80%)",
        workPercentLabel: "80%",
        priceLabel: "EUR 1000.00",
        deductibleLabel: "EUR 800.00",
        warrantyLabel: "24 months",
        notes: "Primary work machine",
        primaryImage: {
          id: "att-1",
          displayName: "receipt.jpg",
          type: "PHOTO",
          mimeType: "image/jpeg",
          fileSizeLabel: "1.2 MB",
          exists: true,
          isImage: true,
          imageDataUri: "data:image/jpeg;base64,abc123",
          embedError: false,
        },
        attachments: [],
      },
    ];
    model.imageAppendixGroups = [
      {
        itemId: "item-1",
        itemTitle: "Laptop",
        images: [
          {
            id: "att-1",
            displayName: "receipt.jpg",
            type: "PHOTO",
            mimeType: "image/jpeg",
            fileSizeLabel: "1.2 MB",
            exists: true,
            isImage: true,
            imageDataUri: "data:image/jpeg;base64,abc123",
            embedError: false,
          },
        ],
      },
    ];
    model.nonImageAttachments = [
      {
        itemTitle: "Laptop",
        fileName: "invoice.pdf",
        attachmentType: "RECEIPT",
        mimeType: "application/pdf",
        fileSizeLabel: "312.0 KB",
        status: "ok",
      },
    ];

    const options: PdfRenderOptions = {
      pageSize: "A4",
      imageLayout: "HYBRID",
      imageQuality: "HIGH",
    };

    const html = renderPdfHtml(model, options);
    expect(html).toContain("Item Details");
    expect(html).toContain("Attachment Appendix");
    expect(html).toContain('src="data:image/jpeg;base64,abc123"');
    expect(html).toContain("invoice.pdf");
  });

  it("uses localized template labels from the document model", () => {
    const model = createBaseModel();
    model.labels = {
      subtitleTaxYear: "Steuerjahr",
      meta: {
        generated: "Erstellt",
        locale: "Sprache/Format",
        currency: "Waehrung",
        detailPages: "Detailseiten",
        timestamp: "Zeitstempel",
        yes: "Ja",
        no: "Nein",
      },
      table: {
        title: "Titel",
        date: "Datum",
        category: "Kategorie",
        usagePercent: "Nutzung %",
        price: "Preis",
        deductible: "Absetzbar",
        totals: "Summen",
      },
      sections: {
        itemDetails: "Eintragsdetails",
        attachmentAppendix: "Anhang",
        nonImageAttachments: "Nicht-Bild Anhaenge",
      },
      detail: {
        purchaseDate: "Kaufdatum",
        category: "Kategorie",
        vendor: "Haendler",
        usage: "Nutzungsart",
        workShare: "Arbeitsanteil",
        price: "Preis",
        deductible: "Absetzbar",
        warranty: "Garantie",
        notes: "Notizen",
        attachments: "Anhaenge",
      },
      appendix: {
        imageGroupedHint: "Bildvorschauen nach Eintrag gruppiert.",
        noImageAttachments: "Keine Bildanhaenge gefunden.",
        noImageAttachmentsInItem: "Keine Bildanhaenge verfuegbar.",
        noNonImageAttachments: "Keine Nicht-Bild Anhaenge.",
      },
      nonImageTable: {
        item: "Eintrag",
        file: "Datei",
        type: "Typ",
        mime: "MIME",
        size: "Groesse",
        status: "Status",
      },
      attachment: {
        statusMissing: "fehlt",
        statusPreviewUnavailable: "Vorschau nicht verfuegbar",
        statusOk: "ok",
        placeholderImageMissing: "Bilddatei fehlt",
        placeholderPreviewUnavailable: "Vorschau nicht verfuegbar",
        placeholderNoImageAttachment: "Kein Bildanhang",
        placeholderNoImagePreviewForItem: "Keine Bildvorschau fuer diesen Eintrag.",
        noAttachments: "Keine Anhaenge",
        noFilesLinked: "Keine Dateien verknuepft.",
      },
    };

    const options: PdfRenderOptions = {
      pageSize: "A4",
      imageLayout: "HYBRID",
      imageQuality: "HIGH",
    };

    const html = renderPdfHtml(model, options);
    expect(html).toContain("Steuerjahr");
    expect(html).toContain("Erstellt:");
    expect(html).toContain("Titel");
    expect(html).toContain("Summen");
  });
});
